apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pageserver-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pageserver
spec:
  selector:
    app.kubernetes.io/name: neon-pageserver
  ports:
    - protocol: TCP
      name: pg-port
      port: 6400
      targetPort: 6400
    - protocol: TCP
      name: http-port
      port: 9898
      targetPort: 9898

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageserver-deployment
  labels:
    app: neon-pageserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neon-pageserver
  template:
    metadata:
      labels:
        app: neon-pageserver
    spec:
      containers:
        - name: pageserver
          image: perconalab/neon:latest
          command: ["pageserver"]
          args: ["-D", "/data", "-c", "broker_endpoint='http://storage-broker.default.svc.cluster.local'", "-c", "listen_pg_addr='0.0.0.0:6400'", "-c", "listen_http_addr='0.0.0.0:9898'", "-c", "id=1", "-c", "pg_distrib_dir='/opt/neondatabase-neon/pg_install'"]
          volumeMounts:
            - mountPath: "/data"
              name: pageserver-data
      volumes:
        - name: pageserver-data
          persistentVolumeClaim:
            claimName: pageserver-vol
