apiVersion: v1
kind: Service
metadata:
  name: safekeepers
spec:
  selector:
    app.kubernetes.io/name: safekeeper
  ports:
    - protocol: TCP
      name: pg-port
      port: 5454
      targetPort: 5454
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 7676
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safekeeper-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safekeeper
  labels:
    app.kubernetes.io/name: safekeeper
    app: neon-safekeeper
spec:
  serviceName: safekeepers
  replicas: 3
  selector:
    matchLabels:
      app: neon-safekeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: safekeeper
        app: neon-safekeeper
    spec:
      containers:
        - name: safekeeper
          image: perconalab/neon:latest
          ports:
            - containerPort: 5454
            - containerPort: 7676
          env:
            - name: pod_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - "bash"
            - "-c"
            - |
              export SAFEKEEPER_ID=$((${pod_id##*-}+1))
              echo $SAFEKEEPER_ID
              mkdir /data/$SAFEKEEPER_ID
              safekeeper -D /data/$SAFEKEEPER_ID --broker-endpoint http://storage-broker.default.svc.cluster.local -l 0.0.0.0:5454 --listen-http 0.0.0.0:7676 --id $SAFEKEEPER_ID
          volumeMounts:
            - mountPath: "/data"
              name: safekeeper-data
      volumes:
        - name: safekeeper-data
          persistentVolumeClaim:
            claimName: safekeeper-vol
