apiVersion: v1
kind: Pod
metadata:
  name: storage-broker
spec:
  containers:
    - name: storage-broker
      image: perconalab/neon:latest
      command: ["storage_broker"]
      args: ["-l", "0.0.0.0:50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: storage-broker
spec:
  selector:
    app.kubernetes.io/name: storage-broker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

