apiVersion: v1
kind: Service
metadata:
  name: storage-broker
spec:
  selector:
    app.kubernetes.io/name: storage-broker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-broker
  labels:
    app: storage-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-broker
  template:
    metadata:
      labels:
        app: storage-broker
    spec:
      containers:
        - name: storage-broker
          image: perconalab/neon:latest
          command: ["storage_broker"]
          args: ["-l", "0.0.0.0:50051"]
